/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
object EvenFibonacci {
  def GenerateSeriesSum(): Unit ={
    var a:Int = 1;
    var b:Int = 2;
    var sum:Int =0;
    var nextNum:Int = 0;
    //println(a)
    while(b <= 4000000) {
      //println(b)
      if(b%2==0)
        sum = sum + b
      nextNum = a + b
      a = b
      b = nextNum
    }
    println("sum of even fibonacci numbers below 4 million is "+sum)
  }
  def main(args:Array[String]): Unit =  {
    GenerateSeriesSum()
  }
}
